modules:
  format: true
  msg: true
  local: true
  games: true
  tags: true # TODO: Add this module
  tab: true
  color: true # TODO: Add this module
  ping: true
  filter: true # TODO: Add this module - anti-spam, anti-advertise, anti-caps, anti-unicode atd.