chat-formats:
  default: "<gray>[<white>%player%<gray>]: <white>%message%"
  vip: "<gold>[VIP] <gray>[<white>%player%<gray>]: <white>%message%"
  owner: "<red>[Owner] <gray>[<white>%player%<gray>]: <white>%message%"

local-chat:
  radius: 100
  enabled: true

chat-games:
  enabled: true
  rewards:
    - "give %player% diamond 1"
    - "eco give %player% 100"

tags:
  vip: "<gold>[VIP]"
  owner: "<red>[Owner]"