modules:
  chat_format: true
  msg: true
  local_chat: true
  chat_games: true
  tags: true
  chat_color: true # TODO: Add this module
  ping: true # TODO: Add this module
  chat_filter: true # TODO: Add this module
  chat_anti_spam: true # TODO: Add this module
  chat_anti_advertise: true # TODO: Add this module
  chat_anti_caps: true # TODO: Add this module

chat_formats:
  owner: "<red>[Owner] <gray>[<white>%player_name%<gray>]: <white>%message%"
  vip: "<gold>[VIP] <gray>[<white>%player_name%<gray>]: <white>%message%"
  default: "<gray>[<white>%player_name%<gray>]: <white>%message%"

msg:
  message_receiver: "<gray>[<white>%player_name%<gray> -> <white>%target_name%<gray>]: <white>%message%"
  message_sender: "<gray>[<white>%player_name%<gray> -> <white>%target_name%<gray>]: <white>%message%"
  message_usage: "<red>Usage: /msg <player> <message>"
  alias:
    - "msg"
    - "tell"
    - "whisper"
    - "w"
    - "m"
    - "pm"
    - "dm"
    - "message"
    - "r"

local_chat:
  radius: 100

chat_games:
  rewards:
    - "give %player_name% diamond 1"
    - "eco give %player_name% 100"