modules:
  chat_format: true
  msg: true
  local_chat: true
  chat_games: true
  tags: true

chat_formats:
  owner: "<red>[Owner] <gray>[<white>%player%<gray>]: <white>%message%"
  vip: "<gold>[VIP] <gray>[<white>%player%<gray>]: <white>%message%"
  default: "<gray>[<white>%player%<gray>]: <white>%message%"

msg:
  message_receiver: "<gray>[<white>%player%<gray> -> <white>%target%<gray>]: <white>%message%"
  message_sender: "<gray>[<white>%player%<gray> -> <white>%target%<gray>]: <white>%message%"
  message_usage: "<red>Usage: /msg <player> <message>"
  alias:
    - "msg"
    - "tell"
    - "whisper"
    - "w"
    - "m"
    - "pm"
    - "dm"
    - "message"
    - "r"

local_chat:
  radius: 100

chat_games:
  rewards:
    - "give %player% diamond 1"
    - "eco give %player% 100"