name: NotChat
version: "0.1-DEV"
main: com.notmarra.notchat.NotChat
authors:
  - "NotMarra"
  - "TheNoiselessNoise"
api-version: "1.21"
permissions:
  notchat.ping:
    description: Allows players to ping others
    default: true
  notchat.ping.receive:
    description: Allows players to receive pings
    default: true
  notchat.ping.reload:
    description: Allows players to reload the configuration
    default: op
  notchat.filter.bypass:
    description: Allows players to bypass the chat filter
    default: op
  notchat.filter.reload:
    description: Allows players to reload the configuration
    default: op
  notchat.color:
    description: Allows players to set their chat color
    default: op
  notchat.color.reload:
    description: Allows players to reload the configuration
    default: op
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    NotLib:
      load: BEFORE
      required: true
