name: NotChat
version: '0.1-DEV'
main: com.notmarra.notchat.NotChat
authors:
  - "NotMarra"
  - "TheNoiselessNoise"
api-version: '1.21'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false